version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
     - image: php:7.1-apache
       environment:
         - DB_NAME=picili
         - DB_HOST=localhost
         - DB_NAME_TESTING=picili-testing
         - DB_PASSWORD=password
     - image: mysql:5.7
       environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_DATABASE=picili
     - image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
     - image: laradock/php-fpm:1.4-71
    working_directory: /picili
    steps:
     # install git
     - run: 
         name: Install packages
         command: apt-get -qq update; apt-get -y install git libpng-dev mysql-client
     - run:
         name: Install PHP extensions
         command: docker-php-ext-install pdo gd
     - checkout
     # install composer
     - run:
        name: Install Composer
        command: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer
    # install php packages/dependencies
     - run: 
         name: Install API php packages/dependencies
         command: |
           cd www-workspace/user-api-laravel && composer install
     - run: 
         name: Install AUTO php packages/dependencies auto
         command: |
           cd www-workspace/auto && composer install
     # run migrations
     - run: 
         name: Run migrations
         command: |
           www-workspace/migrations.sh
     # run tests
     - run:  
         name: API tests
         command: |
           www-workspace/user-api-laravel/vendor/bin/phpunit
     - run:  
         name: AUTO tests
         command: |
           www-workspace/auto/vendor/bin/phpunit
