version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
     - image: php:7.1-apache
     - image: mysql:5.7
       environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_DATABASE=picili
     - image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
     - image: laradock/php-fpm:1.4-71
    working_directory: /picili
    steps:
     - checkout
     - run:
        name: Install Composer
        command: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer
     - run: cd www-workspace/user-api-laravel && php composer.phar install