# circle.yml
machine:
  pre:
    - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
    - sudo apt-get --purge autoremove -y mysql-server
  services:
    - docker
dependencies:
  pre:
    - curl -L https://github.com/docker/compose/releases/download/1.8.0-rc2/docker-compose-`uname -s`-`uname -m` > ../bin/docker-compose && chmod +x ../bin/docker-compose
    - docker-compose pull
  override:
    - echo 'skip dependencies-override'
test:
  pre:
    - echo 'skip test-pre'
  override:
    - docker-compose up 